auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: LaiYongqiang's Blog
url: http://laiyongqiang.github.io
feed: /atom.xml
author_info: <a href="http://laiyongqiang.github.io">LaiYongqiang</a>
